[package]
name = "musmove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
audiotags = "0.4.1"
id3 = "1.7.0" 
rand = "0.8.5"
